# Generated by Django 5.1.4 on 2024-12-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alter_cliente_comercio_alter_comercio_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comercio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_coder.comercio'),
        ),
    ]
